runtime: php74

handlers:
    - url: /(.*\.(gif|png|PNG|jpg|css|js|yaml|svg|tiff|woff|woff2|ico))$
      static_files: public/\1
      upload: public/.*\.(gif|png|PNG|jpg|css|js|yaml|svg|tiff|woff|woff2|ico)$

    - url: /.*
      secure: always
      redirect_http_response_code: 301
      script: auto

env_variables:
  ## Put production environment variables here.
  LOG_CHANNEL: $DEV_LOG_CHANNEL
  APP_KEY: $DEV_APP_KEY
  APP_STORAGE: $DEV_APP_STORAGE
  VIEW_COMPILED_PATH: $DEV_VIEW_COMPILED_PATH
  CACHE_DRIVER: $DEV_CACHE_DRIVER
  SESSION_DRIVER: $DEV_SESSION_DRIVER
  ## Set these environment variables according to your CloudSQL configuration.

  DB_DATABASE: $DEV_DB_DATABASE
  DB_USERNAME: $DEV_DB_USERNAME
  DB_PASSWORD: $DEV_DB_PASSWORD
  DB_SOCKET: $DEV_DB_SOCKET

  ##Laravel Specific
  APP_NAME: $DEV_APP_NAME
  APP_ENV: $DEV_APP_ENV
  APP_DEBUG: $DEV_APP_DEBUG
  APP_URL: $DEV_APP_URL

  DB_CONNECTION: $DEV_DB_CONNECTION
  DB_CONNECTION_CACHE: $DEV_DB_CONNECTION_CACHE
  DB_CONNECTION_DEV: $DEV_DB_CONNECTION_DEV
  DB_CONNECTION_BRAWL: $DEV_DB_CONNECTION_BRAWL
  DB_HOST: $DEV_DB_HOST
  DB_DATABASE_CACHE: $DEV_DB_DATABASE_CACHE
  DB_DATABASE_DEV: $DEV_DB_DATABASE_DEV

  BATTLENET_KEY: $DEV_BATTLENET_KEY
  BATTLENET_SECRET: $BATTLENET_SECRET
  BATTLENET_REDIRECT_URI: $BATTLENET_REDIRECT_URI

  BROADCAST_DRIVER: $DEV_BROADCAST_DRIVER
  CACHE_TABLE: $DEV_CACHE_TABLE
  CACHE_PREFIX: $DEV_CACHE_PREFIX
  QUEUE_CONNECTION: $DEV_QUEUE_CONNECTION
  SESSION_TABLE: $DEV_SESSION_TABLE
  SESSION_LIFETIME: $DEV_SESSION_LIFETIME
