services:
  heroesprofile:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - 8000:8000
    depends_on:
      - database

  database:
    image: mariadb:10.7
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: heroesprofile
      MARIADB_USER: heroesprofile
      MARIADB_PASSWORD: heroesprofilepassword
