# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ikuanyshbekov/app-yaml-env-compiler@v1.1
        env:
          DB_DATABASE: ${{ secrets.DEV_DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DEV_DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DEV_DB_PASSWORD }}
          DB_SOCKET: ${{ secrets.DEV_DB_SOCKET }}
          DB_HOST: ${{ secrets.DEV_DB_HOST }}
          DB_DATABASE_CACHE: ${{ secrets.DEV_DB_DATABASE_CACHE }}
          DB_DATABASE_DEV: ${{ secrets.DEV_DB_DATABASE_DEV }}
          BATTLE.NET_KEY: ${{ secrets.DEV_BATTLENET_KEY }}
          BATTLE.NET_SECRET: ${{ secrets.DEV_BATTLENET_SECRET }}
          BATTLE.NET_REDIRECT_URI: ${{ secrets.DEV_BATTLENET_REDIRECT_URI }}
          SESSION_TABLE: ${{ secrets.DEV_SESSION_TABLE }}


      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_AUTH }}
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
        with:
          args: app deploy app.yaml
